<a href="https://colab.research.google.com/github/Vishu-Gupta/PyTorch_ZTM/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

Major Resource for the course is : https://www.learnpytorch.io/00_pytorch_fundamentals/ 

In [1]:
 import torch
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt
 print(torch.__version__)

1.13.1+cu116


## Introduction to tensors

# Creating tensors

PyTorch tensors are created using torch.Tensor()

In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get the python int 
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7,7])

In [6]:
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7,8],
                       [9,10]])

print(MATRIX.ndim)


2


In [10]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0][1]

tensor(8)

In [14]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

In [15]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

 ### Random tensors

 Why random tensors?

 Random tensors are important because many NN learn is that they start with random numbers and then adjust nos to better represent the data

In [19]:
# Create a random tensor of size(3,4)

random_tensor = torch.rand(3,4)


In [20]:
random_tensor

tensor([[0.7557, 0.3958, 0.6287, 0.1129],
        [0.0708, 0.4770, 0.4766, 0.0910],
        [0.1322, 0.4179, 0.5920, 0.1650]])

In [21]:
random_tensor.ndim

2

In [22]:
# Create a random tensor with a similar shape to an image

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, weight, and colour channel and can be reversed if its color channel, height , width

random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [23]:
# Create a tensor of all zeros

zero = torch.zeros(size=(3,4))

zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors - like 

In [27]:
# Use torch.range()

torch.range(0,10)

<ipython-input-27-8ff1b355b43d>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# since torch range is deprectaed , we can use torch.arange

one_to_ten = torch.arange(0,10)

In [29]:
# add step

torch.arange(start=0,end=1000,step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# Creating tensors like i.e replicating the shape of another tensor

ten_zeros  = torch.zeros_like(input = one_to_ten)

In [31]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types

In [32]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None)

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, # what datatype tensor is float32,float16,float64 etc
                               device = None, # in case of gpu available we can change it to gpu, otherwise it can be cpu , so what device is tensor on
                               requires_grad=False) # if pytorch should track gradients when doing calculations

In [35]:
# create float16 tensor

float_16_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [36]:
float_16_tensor.dtype

torch.float16

In [37]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

 ## Getting information from tensors
 
 1. Datatype = torch.dtype

 2. Shape = torch.shape

 3. Device = torch.device

In [38]:
some_tensor = torch.rand(size=(3,4))
print("Datatype is ", some_tensor.dtype)
print("Shape is ", some_tensor.shape)
print("Device is ", some_tensor.device)


Datatype is  torch.float32
Shape is  torch.Size([3, 4])
Device is  cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [39]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [40]:
tensor*10

tensor([10, 20, 30])

In [41]:
tensor- 10

tensor([-9, -8, -7])

In [42]:
# try out in-built functions

torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing muliplication
* Element wise
* Matrix Multiplication - dot product can be done as matmul or @

There are two main rules for performing matrix multiplication
1. The **inner dimensions** need to match :
* `(3,2)@(3,2)` won't work
* `(2,3)@(3,2)` will work
2. The resulting matrix has the shape of **outer dimensions**:
* `(3,2)@(2,3)` will generate (3,3) matrix

In [43]:
print(tensor,'*',tensor)
tensor*tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])


tensor([1, 4, 9])

In [44]:
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
torch.matmul(tensor,tensor)


tensor(14)

In [46]:
# see dimensions of correct multiplication
torch.matmul(torch.rand(size=(3,2)), torch.rand(size=(2,3))).shape

torch.Size([3, 3])

 # Finding the min, max , sum etc (tensor aggregation)


In [47]:
# create a tensor
x = torch.arange(0,10)


In [48]:
# minimum 
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [49]:
# max
torch.max(x), x.max()

(tensor(9), tensor(9))

In [50]:
# find the mean
# torch.mean requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) 

tensor(4.5000)

In [51]:
#find the sum
torch.sum(x), x.sum()

(tensor(45), tensor(45))

In [52]:
# find the positional  max
# return the position in tensor where the maximum value occurs
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [53]:
# find the positional min 
# return the position in tensor where 
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [54]:
x[9]

tensor(9)

## Reshaping , stacking , squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined Shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors in a specific direction
* Squeeze - remove all `1` dimensiions from a tensor
* UnSqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensioons permuted ( swapped ) in a certain way

In [55]:
# Create a tensor
import torch

x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [56]:
# Add an extra dimension
# reshape needs to be compatible with the original shape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [57]:
# Change the view
z = x.view(1,9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [58]:
# Changing z changes x ( because a view of tensor shares the same memory of the original)
z[:,0]=5

z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [59]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [60]:
# torch.squeeze() - removes all dingle dimensions from the tensor
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
y = torch.squeeze(x)
y.size()
y = torch.squeeze(x, 0)
y.size()
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [61]:
# torch.permute rearranges the tensor dimensions

x = torch.rand(size=(2,3,5))
p_x = torch.permute(x,(2,0,1))
x.shape , p_x.shape

(torch.Size([2, 3, 5]), torch.Size([5, 2, 3]))

In [62]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)

## Indexing(selecting data from tensors)
Indexing with Pytorch is similar to indexing with Numpy

In [63]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [64]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
# lets index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [66]:
# Lets index on last bracket
x[0][0][0]

tensor(1)

In [67]:
# : can be used to select all of a target dimension

x[:,0]

tensor([[1, 2, 3]])

In [68]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [69]:
# get all values of 0 dimension but only 1 index value of 1st and 2nd dimension

x[:,1,1]

tensor([5])

## PyTorch tensors and Numpy

NumPy is a popular scientific Python numerical computing library.

And Because of this, PyTorch has funcitonality to interact with it
* NumPy to PyTorch
* PyTorch to NumPy

In [70]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)

tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [71]:
tensor.dtype  # Warning , numpy has float64 dtype which gets reflected in PyTorch

torch.float64

In [72]:
# change the value of array, what will this do to tensor?
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
array += 1
array,tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [74]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a NN learns:
`start with random numbers -> tensor operations -> update random numbers`

To reduce the randomness, comes the concept of **random seed**

Essentially what the random seed does is 'flavour' the randomness


In [75]:
import torch
# create 2 random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.9883, 0.7779, 0.1357, 0.2129],
        [0.9428, 0.7621, 0.2405, 0.0010],
        [0.0406, 0.9424, 0.0543, 0.2811]])
tensor([[0.5947, 0.1025, 0.0548, 0.3006],
        [0.7829, 0.7919, 0.2473, 0.5574],
        [0.0734, 0.2088, 0.2868, 0.9583]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [76]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_torch_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) 
random_torch_D = torch.rand(3,4)
print(random_torch_C == random_torch_C)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs ( and making faster computations)


### 1. Getting a GPU
1. Easiest - use Google colab for a free GPU
2. Use your own GPU - takes a little bit of setup and requires investment
3. Use cloud computing- GCP, AWS , Azure

### 2. Check for GPU access

In [77]:
# check for GPU access with PyTorch

import torch

torch.cuda.is_available()

False

In [78]:
# setup device agnostic code

device ='cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [79]:
torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

### 3. Putting tensors (and models) on the GPU

The reason is to  achieve faster computations

In [80]:
# creat a tensor (default is on CPU)

tensor = torch.tensor([1,2,3])
# tensor not on GPU

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [81]:
# move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to CPU

In [82]:
# If tensor is on GPU , can't tranform it to NumPy

#need to call it as 

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()